
# This file is automatically generated, you probably don't want to edit this

jamoviBAanalysisOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jamoviBAanalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            method1 = NULL,
            method2 = NULL,
            ciDisplay = TRUE,
            ciShading = TRUE, ...) {

            super$initialize(
                package='blandr',
                name='jamoviBAanalysis',
                requiresData=TRUE,
                ...)

            private$..method1 <- jmvcore::OptionVariable$new(
                "method1",
                method1)
            private$..method2 <- jmvcore::OptionVariable$new(
                "method2",
                method2)
            private$..ciDisplay <- jmvcore::OptionBool$new(
                "ciDisplay",
                ciDisplay,
                default=TRUE)
            private$..ciShading <- jmvcore::OptionBool$new(
                "ciShading",
                ciShading,
                default=TRUE)

            self$.addOption(private$..method1)
            self$.addOption(private$..method2)
            self$.addOption(private$..ciDisplay)
            self$.addOption(private$..ciShading)
        }),
    active = list(
        method1 = function() private$..method1$value,
        method2 = function() private$..method2$value,
        ciDisplay = function() private$..ciDisplay$value,
        ciShading = function() private$..ciShading$value),
    private = list(
        ..method1 = NA,
        ..method2 = NA,
        ..ciDisplay = NA,
        ..ciShading = NA)
)

jamoviBAanalysisResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bland-Altman analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Bland-Altman table",
                rows=1,
                columns=list(
                    list(
                        `name`="observations", 
                        `title`="No of observations", 
                        `type`="number"),
                    list(
                        `name`="bias", 
                        `title`="Bias", 
                        `type`="number"),
                    list(
                        `name`="upperLOA", 
                        `title`="Upper limit of agreement", 
                        `type`="number"),
                    list(
                        `name`="lowerLOA", 
                        `title`="Lower limit of agreement", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Bland-Altman Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

jamoviBAanalysisBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jamoviBAanalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'blandr',
                name = 'jamoviBAanalysis',
                version = c(1,0,0),
                options = options,
                results = jamoviBAanalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bland-Altman analysis
#'
#' 
#' @param data .
#' @param method1 .
#' @param method2 .
#' @param ciDisplay .
#' @param ciShading .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
jamoviBAanalysis <- function(
    data,
    method1,
    method2,
    ciDisplay = TRUE,
    ciShading = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jamoviBAanalysis requires jmvcore to be installed (restart may be required)')

    options <- jamoviBAanalysisOptions$new(
        method1 = method1,
        method2 = method2,
        ciDisplay = ciDisplay,
        ciShading = ciShading)

    results <- jamoviBAanalysisResults$new(
        options = options)

    analysis <- jamoviBAanalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
