
# This file is automatically generated, you probably don't want to edit this

jamoviBAnormalityOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jamoviBAnormalityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            method1 = NULL,
            method2 = NULL, ...) {

            super$initialize(
                package='blandr',
                name='jamoviBAnormality',
                requiresData=TRUE,
                ...)

            private$..method1 <- jmvcore::OptionVariable$new(
                "method1",
                method1)
            private$..method2 <- jmvcore::OptionVariable$new(
                "method2",
                method2)

            self$.addOption(private$..method1)
            self$.addOption(private$..method2)
        }),
    active = list(
        method1 = function() private$..method1$value,
        method2 = function() private$..method2$value),
    private = list(
        ..method1 = NA,
        ..method2 = NA)
)

jamoviBAnormalityResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plotNormality = function() private$.items[["plotNormality"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bland-Altman normality testing")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotNormality",
                width=600,
                height=450,
                renderFun=".plot"))}))

jamoviBAnormalityBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jamoviBAnormalityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'blandr',
                name = 'jamoviBAnormality',
                version = c(1,0,0),
                options = options,
                results = jamoviBAnormalityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bland-Altman normality testing
#'
#' 
#' @param data .
#' @param method1 .
#' @param method2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotNormality} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jamoviBAnormality <- function(
    data,
    method1,
    method2) {

    if ( ! requireNamespace('jmvcore'))
        stop('jamoviBAnormality requires jmvcore to be installed (restart may be required)')

    options <- jamoviBAnormalityOptions$new(
        method1 = method1,
        method2 = method2)

    results <- jamoviBAnormalityResults$new(
        options = options)

    analysis <- jamoviBAnormalityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
